name: Build and Push Image to Dockerhub

on:
  push:
    tags:
      - '*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Clone MinIO upstream
        run: |
          git clone https://github.com/minio/minio.git
          cd minio
          git checkout ${{ steps.extract_tag.outputs.TAG_NAME }}

      - name: Build Docker image
        run: |
          cd minio
          TAG=docker.io/sixteenone/minio:${{ steps.extract_tag.outputs.TAG_NAME }} make docker
          docker tag docker.io/sixteenone/minio:${{ steps.extract_tag.outputs.TAG_NAME }} docker.io/sixteenone/minio:latest


      - name: Push Docker images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker push docker.io/sixteenone/minio:${{ steps.extract_tag.outputs.TAG_NAME }}
          docker push docker.io/sixteenone/minio:latest